# -*- coding: utf-8 -*-
"""Image Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YdWcI6FRfWxKQkQU2mLIyTFbkyAXa_mh
"""

import os
import numpy as np
from PIL import Image

def preprocess_and_save_images(input_folder, output_folder):
    file_count = 1

    for filename in os.listdir(input_folder):
        if filename.lower().endswith((".png", ".jpg", ".jpeg")):  # Check for image files
            image_path = os.path.join(input_folder, filename)
            save_path = os.path.join(output_folder, f"preprocessed_image_{file_count}.npy")

            img = Image.open(image_path)
            img = img.convert("L")  # Convert to grayscale
            img = img.resize((224, 224))  # Resize
            img_array = np.array(img, dtype=np.float32) / 255.0  # Normalize

            np.save(save_path, img_array)  # Save as .npy file
            print(f"Processed and saved: {save_path}")
            file_count += 1

input_folder = "/content/drive/MyDrive/Synthetic image generation/generated"
output_folder = "/content/drive/MyDrive/Synthetic image generation/Preprocessed"  # Folder must exist
preprocess_and_save_images(input_folder, output_folder)

